spring.application.name=watchvault-backend-springboot
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=watchvault_db;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=watchvault_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.security.session-timeout-minutes=15

server.address=0.0.0.0
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:ssl/watchvault-local.p12
server.ssl.key-store-password=watchvault
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=watchvault
